### PR TITLE
add support for static lazy properties

### PR DESCRIPTION
**Pull request by erancahana**
i added support for static properties and tested with several different variations which all worked for me.
i would appreciate if you could take a quick glance to double check since i've never done any cecil or fody work before.

the code for handling static properties is very similar to regular properties with slight alterations to the instructions in order to reference static fields, and omitting 'this' instance args.

do you think the unit test i added will suffice, or should i add something more exhaustive?

thanks!

### CODE REVIEW

**Comment by tom-englert** [comment]
@qwertio are you going to fix this?

**Comment by tom-englert** [comment]
@qwertio will you continue on this?

**Comment by erancahana** [comment]
Hi, yeah I'm sorry I haven't been as responsive, I only now saw your previous message. A bunch of critical systems went down and I had almost no free time recently.

I need to check why the tests failed. I'll give it another look right now.

**Comment by erancahana** [comment]
ok, working now. i fixed my unit tests for testing static, and made them more comprehensive.
i'd appreciate it if you could just take a glance at my changes to Processor since I've never done any Fody development before and it's been a decade or so since i've done anything with the IL.

**Comment by tom-englert** [comment]
:+1:

**Comment by tom-englert** [comment]
fixes #1

**Comment by erancahana** [comment]
hey i just wanted to thank you for helping me through this. i hoped i didnt make too much of a mess of it, since updated the FodyTools files locally i hadn't realized that it was actually a submodule, so that it didn't commit the changes to the Lazy repo. anyways, thanks for the help!

**Pull request merged**
